version: "3"

tasks:
  build:
    desc: Build pkg-init
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/pkg-init main.go

  run:
    desc: Run pkg-init
    cmds:
    - GOFLAGS=-mod=mod go run main.go
