

name: Build pkg-init


on: [push]

jobs:
  Build-pkg-init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.X'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: GOFLAGS=-mod=mod go build main.go

      - name: Test
        run: GOFLAGS=-mod=mod go test main.go
